baseurl = "https://example.com"
languageCode = "en"
title = "Artjom Vinnikov"
author = "Artjom Vinnikov"
theme = "Hucore"
copyright = "&copy; 2017 | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "shortname"
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Artjom Vinnikov"
sharingicons = false

[[menu.main]]
name = "Blog"
weight = 1
url = "/"

[[menu.main]]
name = "Projects"
weight = 2
url = "/projects"

[[menu.main]]
name = "About"
weight = 3
url = "/about"

[params.highlight]
style = "github"
languages = ["javascript", "elixir", "html", "css"]

[[params.social]]
url = "https://github.com/artvinn"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/artjomvinn"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/artjomvinnikov"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"